general {
    lock_cmd = pidof hyprlock || hyprlock       # runs hyprlock if not already running
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after resume
}

# 1. Dim screen brightness after 2.5 minutes (requires brightnessctl)
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10         # save current brightness and set to 10%
    on-resume = brightnessctl -r                # restore saved brightness
}

# 2. Lock screen after 5 minutes
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session          # triggers general.lock_cmd
}

# 3. Turn off displays after 5.5 minutes
listener {
    timeout = 330                                
    on-timeout = hyprctl dispatch dpms off      # screen off
    on-resume = hyprctl dispatch dpms on        # screen on when activity detected
}

# 4. Suspend system after 10 minutes
listener {
    timeout = 600                                
    on-timeout = systemctl suspend              # suspend PC
}
