color0 #49473d
color1 #ffb4ab
color2 #fff7d8
color3 #cbc6b8
color4 #edfce6
color5 #cdc7a9
color6 #cbc6b8
color7 #e6e2de
color8 #949185
color9 #ffb4ab
color10 #fff7d8
color11 #cbc6b8
color12 #edfce6
color13 #cdc7a9
color14 #cbc6b8
color15 #e6e2de

cursor                #e6e2de
cursor_text_color     #141311
background            #141311
foreground            #e6e2de
selection_foreground  #cbc6ba
selection_background  #49473d
active_border_color   #fff7d8
inactive_border_color #49473d
url_color             #fff7d8

active_tab_foreground   #34311c
active_tab_background   #fff7d8
inactive_tab_foreground #cbc6ba
inactive_tab_background #49473d
cursor_trail_color      #cbc6ba
